### ISSUE TITLE
Assist newsrooms with e-commerce tracking in Mailchimp

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#692] opened 2021-11-24 17:29 UTC
Asana: https://app.asana.com/0/1200942827698993/1201001429681524/f
Details: https://docs.google.com/document/d/1s83l3e_kwYnMziNjN4Fhju3lwlrKEMbX6eUuPpZrb7U/edit#heading=h.pea6azcsyo5x

**Comment by adekbadek** [comment] 2022-09-09 13:56
Isn't this a duplicate of https://github.com/Automattic/newspack-popups/issues/671?

**Comment by aschweigert** [comment] 2022-09-09 14:06
Yeah I think at least the gist of it is that we should strongly encourage (or even require) publishers to enable ecommerce tracking in MC when they use Campaigns. I think the tasks were separate because one was more about documentation and the other about seeing if we could do it programmatically. These can probably combined into one issue though.

**Closed** 2022-09-09 15:48 UTC
Labels: Needs documentation, [Priority] Medium, [Effort] Low, won't fix
