### ISSUE TITLE
Overlay campaign settings initially lack "sitewide default" option

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-popups#198] opened 2020-08-20 17:13 UTC
When creating a new Overlay campaign, there's no way to choose "sitewide default." That option only appears after initially publishing the campaign. 

Here's [a video of it](https://cloudup.com/iQXyJhHUn2t)

Here's an image before publishing (note "Publish" is the blue-button option at the top)
"Sitewide default" nowhere in evidence.
![Screen Shot 2020-08-20 at 12 06 40 PM](https://user-images.githubusercontent.com/48489469/90803103-dfe1fa00-e2dd-11ea-8ca1-f62500f579b1.png)
Here's an image after publishing (Note "Update" is now the blue-botton option at the top)
Sitewide default is now an option
![Screen Shot 2020-08-20 at 12 07 14 PM](https://user-images.githubusercontent.com/48489469/90803530-80381e80-e2de-11ea-8c68-9067fd9701b1.png)

**Comment by adekbadek** [comment] 2020-10-22 11:04
Duplicate of #72

**Closed by adekbadek** 2020-10-22 11:04 UTC
