### ISSUE TITLE
Campaigns + Jetpack Slideshow + No AMP = No slideshow in Chrome

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-popups#170] opened 2020-07-08 19:49 UTC
This is a bit of an odd one, originally reported [in the Jetpack repo](https://github.com/Automattic/jetpack/issues/16114), but I found the Newspack Campaigns plugins greatly increased how often in happened, so I'm reporting here, too, in case there's something in the plugin that's causing that.

Both Rivard and Houston Herald have run into this issue:

### Steps to reproduce:

1. Set up a Newspack test site.
2. Enable the Newspack Campaigns plugin (you don't need to do anything else, like create a campaign -- just have the plugin active).
3. Set AMP to transitional mode, or turn it off entirely, so you can view the page without AMP.
4. Add a Slideshow block to a page. 
5. Open the page in an incognito window in Chrome.

The block is there, but isn't visible; it doesn't load all of the classes needed to switch it from `opacity: 0` to `opacity: 1`:

![image](https://user-images.githubusercontent.com/177561/86962964-90be7c00-c118-11ea-9840-4d23d3186888.png)

6. Close the incognito window (to make sure nothing caches).
7. Disable the Newspack Campaigns plugin.
8. Open a fresh incognito window.
9. The slideshow should now display as expected.

Turning on AMP will also make the slideshow display as expected; my best guess is this is related to the campaigns still kind of loading AMP files when the Newspack Campaigns plugin is active. 

Example site (that hopefully hangs around long enough for someone to see it): https://asian-weevil.jurassic.ninja/

**Comment by dkoo** [comment] 2020-07-13 20:24
I looked into this briefly, but haven't had a chance to fully test a solution yet. I found that throttling my connection speed (via Dev Tools > Network) helped me replicate this bug a lot more reliably, which definitely suggests that it has something to do with async functionality and/or race conditions. I tried testing a fix in the Jetpack plugin itself, but I had trouble getting the plugin to run in my environment in dev mode to verify whether that would fix the issue.

Since this issue only seems to happen in non-AMP pages, I wonder if we could bypass the problem in JS by watching for the swiper initialization (maybe using a MutationObserver to observe when it's added to the DOM) and adding the classes or setting the opacity ourselves? More of a bandaid than an ideal solution, but it might help us sidestep the problem without having to wait on Jetpack to fix the bug first. cc @jeffersonrabb

**Comment by dkoo** [comment] 2020-08-04 22:05
I threw myself at this a bit more and I now think the issue is related to AMP scripts being enqueued even when AMP is not active.

When making `$scripts` an empty array on [this line](https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups-inserter.php#L381), the slideshow block renders correctly on the front-end. It seems that enqueuing any AMP extension script causes the block's JS to silently fail. AMP somehow interferes with the resolution of [certain promises](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/slideshow/create-swiper.js#L43) in the Jetpack block code.

@jeffersonrabb I know you've been grappling with the consequences of enqueuing AMP scripts for non-AMP pages, so maybe this is one more reason to consider refactoring to avoid that.

As for the Jetpack issue, we might consider closing it due to the fact that it's not really a Jetpack bug, but one that's caused by the interaction of AMP scripts + Jetpack in a non-AMP environment.

**Comment by jeffersonrabb** [comment] 2020-08-05 14:45
> I now think the issue is related to AMP scripts being enqueued even when AMP is not active.

Strongly suspect you are correct. Before we leave this, I would be curious to know if there is one particular AMP script causing the issue? If so, this might open the door to a quick fix where we refactor just that one piece of functionality. If it turns out to be any AMP script, or the AMP runtime, then it won't really matter.

**Comment by dkoo** [comment] 2020-08-05 15:22
The runtime script doesn't cause the error, but any one of the extension scripts does.

**Comment by tmmbecker** [comment] 2021-07-07 21:08
FWR is running Transitional AMP and ran into this bug in both Chrome and Safari. I was able to reliably reproduce on a [clone](https://fortworth-debug.newspackstaging.com/). Deactivating Campaigns immediately resolved the problem. 

The slideshows also displayed as expected on mobile and when viewing the page in AMP mode.

**Comment by dkoo** [comment] 2021-07-07 22:50
> Disabling campaigns on the post also fixed this.

Yep, this has been the workaround that I recommend when this situation occurs, if AMP can't be turned on for some reason.

**Comment by gamebits** [comment] 2022-08-05 16:16
This is also affecting Noozhawk.

**Comment by dkoo** [comment] 2022-10-20 19:59
Reopened by #995.

**Closed** 2022-11-10 08:29 UTC
Labels: bug, released, non-AMP, released on @alpha, [Priority] Low
