### ISSUE TITLE
Prompt popup segment field doesn’t always work

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#665] opened 2021-11-16 02:11 UTC
reported by Reveal, to reproduce:
- click the sliders icon in the campaign prompt list, 
- type to add a prompt to the segment “Everyone else”
- typeahead works, but then the segment disappears from the box.

Asana: https://app.asana.com/0/1200942827698993/1201001433518112
Details: https://docs.google.com/document/d/1yaRwAQirSrCyNdjqlyGdeALLwrNfrJEkZsKvwM66e_w/edit#heading=h.h5zyg3wdfq9

**Comment by aschweigert** [comment] 2021-11-16 02:12
@adekbadek was unable to reproduce and thinks this might be specific to their site

**Comment by adekbadek** [comment] 2021-11-16 14:14
This would use some clarification. There's a quasi-segment called "Everyone" in the UI, which is not selectable in the modal. This "segment" means that no segment was chosen. 
After creating a segment and calling it "Everyone else", I'm not able to reproduce.

**Comment by dkoo** [comment] 2022-02-21 22:32
I'm able to replicate on the publisher's site, so there is something going on here. Investigating...

**Comment by dkoo** [comment] 2022-02-21 22:48
After deleting and recreating the offending segment (which wasn't assigned to any prompts), I'm able to assign it to any prompt as usual. So I think something must have been "off" with that particular segment's config data. I think we can close this as it doesn't seem code-related after all.

**Closed by dkoo** 2022-02-21 22:48 UTC
Labels: [Priority] Low, [Status] Needs Investigation
