### ISSUE TITLE
Unrecognized AMP Element Errors

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#57] opened 2020-02-04 20:46 UTC
Somewhat frequently the Pop-up fails to appear and this error is seen in the console:

```
error.js:198 [Action] Unrecognized AMP element "amp-animation".​​​ <amp-animation id=​"showAnim" layout=​"nodisplay" class=​"i-amphtml-error i-amphtml-element i-amphtml-layout-nodisplay" hidden i-amphtml-layout=​"nodisplay">​…​</amp-animation>​
hf @ error.js:198
log.js:714 Uncaught (in promise) Error: [Action] Unrecognized AMP element "amp-animation".​​​
    at ab (log.js:714)
    at Xa.f.createError (log.js:352)
    at vf.f.xa (action-impl.js:646)
    at Af (action-impl.js:695)
    at n (action-impl.js:627)
    at action-impl.js:632
    at Array.forEach (<anonymous>)
    at zf (action-impl.js:606)
    at vf.f.trigger (action-impl.js:426)
    at S.push.f.S.Y (amp-position-observer.js:151)
```

**Comment by adekbadek** [comment] 2021-05-24 15:59
Closing due to irreproducibility. If the issue crops up again, please indicate if that's on an AMP page or not.

**Closed by adekbadek** 2021-05-24 15:59 UTC
