### ISSUE TITLE
Time-triggered overlay campaigns do not appear on homepage

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#244] opened 2020-10-05 22:23 UTC
To reproduce:

1. Create an overlay campaign with time-based trigger (e.g. 3 seconds), set to site-wide default
2. Visit the homepage; observe that the campaign is not displayed

**Comment by dkoo** [comment] 2020-10-05 22:50
Hmm, can't replicate this on a new JN site, only on my local site. Not sure if this is replicable after all.

**Comment by jeffersonrabb** [comment] 2020-10-19 13:16
Wasn't this resolved in https://github.com/Automattic/newspack-popups/pull/236?

**Comment by adekbadek** [comment] 2020-10-22 10:57
Cannot reproduce, this was most probably fixed by #232
(Also, duplicate of #217)

**Closed by adekbadek** 2020-10-22 10:57 UTC
Labels: bug
