### ISSUE TITLE
Inline prompt insertion bug

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-popups#519] opened 2021-04-09 22:11 UTC
This is probably due to something similar to (but not the same cause as) #465.

In certain cases (unknown as of yet), inline prompts are not being injected into the correct spot in article content.

[Here's an example](https://oaklandside.org/2021/04/09/oakland-unified-student-learning-schedule/) of a page where the insertion is happening correctly. The "Here's what else is going on" prompt appears correctly at 30% down the article's content.

<img width="824" alt="Screen Shot 2021-04-09 at 4 10 14 PM" src="https://user-images.githubusercontent.com/2230142/114245678-2c05ab80-994e-11eb-992e-a2ab95676a34.png">

Here's an example of a page where the same prompt is being inserted in the wrong spot. In this case, the prompt appears at the very top of the content, visually clashing with another prompt which is (correctly) displayed at 0% of the article content:

<img width="1236" alt="Screen Shot 2021-04-09 at 4 11 11 PM" src="https://user-images.githubusercontent.com/2230142/114245737-417ad580-994e-11eb-919d-6e61ab6d97bd.png">

**Expected**

The prompt should appear 30% into the article content in all cases.

**Comment by adekbadek** [comment] 2021-04-12 08:43
Duplicate of #137 - converting the post to blocks should resolve the issue.

**Closed by adekbadek** 2021-04-12 08:43 UTC
Labels: bug

**Comment by dkoo** [comment] 2021-04-12 15:50
@adekbadek Thanks for confirming!
